[Improvement-3471][common] JSONUtils.toMap It is not necessary to check whether the JSON method is empty again. #3471
apache/incubator-dolphinscheduler pull request #3481
Opened 2020-08-13 07:47 UTC by zhuangchong

## What is the purpose of the pull request

1.JSONUtils.toMap (string JSON) the JSON has been checked for null in the (string JSON) method. There is no need to call the method again to check whether the parameter is empty.

2. processService.delCommandByid processService.queryUdfFunListByids Method name checkstyle

3.DataSourceService.java ProcessService.java Class code checkstyle

## Brief change log
1.JSONUtils.toMap Method parameters have been checked empty

```
if (StringUtils.isEmpty(json)) {
            return null;
        }
```
DataSourceService

```
        if (other != null && !"".equals(other)) {	
            Map<String, String> map = JSONUtils.toMap(other);	
            if (map.size() > 0) {
              ....
            }
        }
```
ProcessService
```
            if(processInstance.getCommandParam() != null){	            
                Map<String, String> processCmdParam = JSONUtils.toMap(processInstance.getCommandParam());
```

2.processService.delCommandByid Change to delCommandById 

processService.queryUdfFunListByids Change to queryUdfFunListByIds 

3.DataSourceService.java ProcessService.java Class code checkstyle

## Verify this pull request

This pull request is code cleanup without any test coverage.

---

## 拉取请求的目的是什么

1.JSONUtils.toMap（String json）方法内部已经对json校验空，没有必要再调用方法是再次校验参数是否为空。
2. processService.delCommandByid processService.queryUdfFunListByids 方法名checkstyle
3.DataSourceService.java ProcessService.java 类代码checkstyle

## 简要变更日志
1.JSONUtils.toMap 方法内 参数已经校验空
```
if (StringUtils.isEmpty(json)) {
            return null;
        }
```
DataSourceService

```
        if (other != null && !"".equals(other)) {	
            Map<String, String> map = JSONUtils.toMap(other);	
            if (map.size() > 0) {
              ....
            }
        }
```
ProcessService
```
            if(processInstance.getCommandParam() != null){	            
                Map<String, String> processCmdParam = JSONUtils.toMap(processInstance.getCommandParam());
```

2.processService.delCommandByid 改成 delCommandById

processService.queryUdfFunListByids 改成 queryUdfFunListByIds 

3.DataSourceService.java ProcessService.java 类代码checkstyle

## 验证此请求

这个请求是代码清理，没有任何测试覆盖。

2020-08-21 02:26 UTC, yangyichao-mango commented
Hi~
Please resolve the conflicts and resolve the sonar reported fail, thx a lot.

2020-10-12 06:02 UTC, gabrywu requested changes

2020-10-12 06:02 UTC, gabrywu commented on dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/EnterpriseWeChatUtils.java
> +            return map.get("access_token");
return map==null?null: map.get("access_token")

2020-11-05 11:15 UTC, CalvinKirs approved these changes
+1

2020-11-15 12:03 UTC, CalvinKirs commented on dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/EnterpriseWeChatUtils.java
> +            return map.get("access_token");
please review.thx

2020-11-18 06:29 UTC, gabrywu approved these changes

2020-11-18 06:30 UTC, merged