[Improvement-4012][common/remote] Json util code integration,remove the remote module json util
apache/incubator-dolphinscheduler pull request #4013
Opened 2020-10-30 10:49 UTC by zhuangchong

#4012

## What is the purpose of the pull request

Json util code integration, remove the remote module json util.

## Brief change log

1.remote model remote JsonSerializer class
2.common model JSONUtils add method

## Verify this pull request

This change added tests and can be verified as follows:
  - *Added JSONUtilsTest to verify the change.*

2020-11-04 12:30 UTC, CalvinKirs requested changes
The pom file of the reomte module still depends on jackson-databind, please delete it?

2020-11-04 12:57 UTC, CalvinKirs commented on dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/JSONUtils.java
> +        String json = "";
Here should be a null operation on obj.

2020-11-05 04:47 UTC, zhuangchong commented
> The pom file of the reomte module still depends on jackson-databind, please delete it?

done.

2020-11-05 04:47 UTC, zhuangchong commented on dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/JSONUtils.java
> +        String json = "";
done.

2020-11-05 10:51 UTC, CalvinKirs approved these changes
+1

2020-11-07 11:37 UTC, dailidong approved these changes
+1
good job

2020-11-07 11:37 UTC, merged