[Feature-4050][server] Spark task support udv inject
apache/incubator-dolphinscheduler pull request #4061
Opened 2020-11-12 08:46 UTC by Eights-Li

## What is the purpose of the pull request

*#4050 Spark Task support user define vars inject*

## Brief change log

  - *Modify SparkTask & SparkArgsUtils*

## Verify this pull request
  - *worker/SparkTaskTest*

2020-11-15 02:37 UTC, dailidong commented
@lgcareer @CalvinKirs please review, thx

2020-11-15 07:02 UTC, CalvinKirs approved these changes
+1

2020-11-16 10:27 UTC, lenboo commented on dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/SparkArgsUtils.java
> +        if (!"local".equals(deployMode)) {
magic number

2020-11-16 10:31 UTC, lenboo commented on dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/spark/SparkTask.java
> +        if (mainJar != null) {
i think it's better to return void if null.

2020-11-16 10:35 UTC, lenboo requested changes
magic number need to be clear

2020-11-17 06:10 UTC, lenboo approved these changes
+1

2020-11-17 07:24 UTC, lgcareer approved these changes
+1

2020-11-17 07:24 UTC, merged